name: run breakout_file.py
true:
  push:
    branches:
    - main
  schedule:
  - cron: 25 15 16 5 *
  - cron: 31-59/15 9 * * mon-fri
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: install python packages
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        '
    - env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        SECRETS_GITHUB_TOKEN: ${{ secrets.SECRETS_GITHUB_TOKEN }}
      name: execute py script
      run: "if [[ ${{ github.event_name }} == 'push' ]]; then\n  python three_line_pattern_detect.py\
        \ \"push\"\nelif [[ ${{ github.event_name }} == 'schedule' ]]; then\n  python\
        \ three_line_pattern_detect.py \"schedule\"\nfi\n"
    - name: commit files
      run: 'git config --local user.email "action@github.com"

        git config --local user.name "GitHub Action"

        git add -A

        git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

        '
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: main
        github_token: ${{ secrets.SECRETS_GITHUB_TOKEN }}
