name: daily three_line_pattern_detect

on:
  push:
    branches:
      - main
      # - ${{ github.head_ref || github.ref_name }}
  # schedule: 
    # - cron: '*/15 10-15 * * mon-fri' # At 10 to 15.59 every 15 min
    # - cron: '31-59/15 9 * * mon-fri' # At 9.31 to 9.59 every 15 min

# jobs:
#   build:
#     runs-on: ubuntu-latest
jobs:
  build:
    # runs-on: ubuntu-20.04-high-performance
    runs-on: macos-latest
    # strategy:
      # matrix:
        # runner_type: [ubuntu-20.04-high-performance]
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run three_line_pattern_detect.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SECRETS_GITHUB_TOKEN: ${{ secrets.SECRETS_GITHUB_TOKEN }}
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            python three_line_pattern_detect.py "60minute"
          elif [[ ${{ github.event_name }} == 'schedule' ]]; then
            python three_line_pattern_detect.py "day"
          fi
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.SECRETS_GITHUB_TOKEN }}
          branch: main
